# Generated by Django 3.1.7 on 2021-03-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='add_date',
            field=models.DateField(auto_now=True),
        ),
    ]
