# Generated by Django 3.1.7 on 2021-03-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210314_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='add_date',
            field=models.DateTimeField(),
        ),
    ]
