# Generated by Django 3.1.7 on 2021-03-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210314_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='charged',
            field=models.BooleanField(default=False),
        ),
    ]
