# Generated by Django 3.1.7 on 2021-03-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bill_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='item_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='item_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
