# Generated by Django 3.1.7 on 2021-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varient',
            name='photo',
        ),
        migrations.AlterField(
            model_name='billitems',
            name='item_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billitems',
            name='item_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
