# Generated by Django 3.1.7 on 2021-03-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210315_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='charged_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customers'),
        ),
        migrations.AddField(
            model_name='billitems',
            name='choosed_varients',
            field=models.ManyToManyField(blank=True, null=True, to='main.Varient'),
        ),
    ]
