# Generated by Django 3.1.7 on 2021-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210316_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='choosed_varients',
            field=models.ManyToManyField(blank=True, to='main.Varient'),
        ),
    ]
