# Generated by Django 3.1.7 on 2021-03-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210316_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
