# Generated by Django 3.1.7 on 2021-03-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_varient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='image',
            field=models.ImageField(blank=True, default='data/images/default.png', null=True, upload_to='images'),
        ),
    ]
