# Generated by Django 3.1.7 on 2021-03-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210318_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
