# Generated by Django 3.1.7 on 2021-04-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210406_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='bill',
            name='items',
            field=models.ManyToManyField(blank=True, to='main.BillItem'),
        ),
    ]
