# Generated by Django 3.1.7 on 2021-04-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210406_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varientname',
            name='varient',
        ),
        migrations.AddField(
            model_name='varient',
            name='varient_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.varientname'),
        ),
    ]
