# Generated by Django 3.1.7 on 2021-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210407_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images'),
        ),
    ]
