# Generated by Django 3.1.7 on 2021-04-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210410_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='quantity_num',
            field=models.IntegerField(default=10),
        ),
    ]
