# Generated by Django 3.1.7 on 2021-04-14 01:32

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_stockitem_quantity_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='quantity_num',
            field=models.IntegerField(default=main.models.StockItem.quantity),
        ),
    ]
