# Generated by Django 3.1.7 on 2021-04-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210414_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity_num',
        ),
    ]
