# Generated by Django 3.2 on 2021-04-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_stockitem_quantity_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
